- src/main/java/ca/gov/dtsstn/passport/api/config/SpringDocConfig.java
OWASP ZAP warned that the security definition in the OpenAPI spec didn't meet the required naming pattern. This fixes that issue.
> Fix OWASP ZAP warning about swagger

- src/main/java/ca/gov/dtsstn/passport/api/config/SpringDocConfig.java
- src/main/resources/application-local.yaml.sample
After doing some debugging I've realized that specifying servers in the configuration will break making calls to localhost. So I'm removing it.
> Permanently remove swagger server list

- src/main/java/ca/gov/dtsstn/passport/api/config/JmsConfig.java
- src/main/java/ca/gov/dtsstn/passport/api/service/domain/PassportStatus.java
Add Jackson as JMS message converter to store JSON instead of serialized Java Object in the message queue.
`@JsonDeserialize(as = ImmutablePassportStatus.class)` is added otherwise Jackson cannot deserialize the immutable interface.
> Add Jackson as JMS message converter

- src/main/java/ca/gov/dtsstn/passport/api/web/model/BirthDate.java
- src/main/java/ca/gov/dtsstn/passport/api/web/model/CertificateApplication.java
- src/main/java/ca/gov/dtsstn/passport/api/web/model/CertificateApplicationApplicant.java
- src/main/java/ca/gov/dtsstn/passport/api/web/model/CertificateApplicationDate.java
- src/main/java/ca/gov/dtsstn/passport/api/web/model/CertificateApplicationIdentification.java
- src/main/java/ca/gov/dtsstn/passport/api/web/model/CertificateApplicationStatus.java
- src/main/java/ca/gov/dtsstn/passport/api/web/model/CreateCertificateApplicationRequest.java
- src/main/java/ca/gov/dtsstn/passport/api/web/model/PersonContactInformation.java
- src/main/java/ca/gov/dtsstn/passport/api/web/model/PersonName.java
The intent of this PR is to introduce NIEM compliant models for a passport application (known as a _certificate_ in NIEM parlance).
**They are not used yet, and are submitted here simply to make future FUNCTIONAL PRs easier to manage.**
The models in this PR conform to the following data schema provided by the ESDC interop team:
``` json
{
"CertificateApplication": {
"CertificateApplicationApplicant": {
"BirthDate": {
"Date": "2000-01-01"
},
"PersonContactInformation": {
"ContactEmailID": "user@example.com"
},
"PersonName": {
"PersonGivenName": [
"John"
],
"PersonSurName": "Doe"
}
},
"CertificateApplicationDate": {
"Date": "2022-01-01"
},
"CertificateApplicationIdentification": [
{
"IdentificationCategoryText": "Application Register SID",
"IdentificationID": "ABCD1234"
},
{ …
```
> Add NIEM models for passport (aka "certificate")

- src/main/java/ca/gov/dtsstn/passport/api/event/PassportStatusSearchEvent.java
- src/main/java/ca/gov/dtsstn/passport/api/event/listener/MetricsGeneratingEventListener.java
- src/main/java/ca/gov/dtsstn/passport/api/web/PassportStatusController.java
Application will now count the following:
- `esrf_requests`
- `esrf_requests.sent`
- `esrf_requests.failed`
- `passport_statuses.created`
- `passport_statuses.created.approved`
- `passport_statuses.created.in_examination`
- `passport_statuses.created.rejected`
- `passport_statuses.created.unknown`
- `passport_statuses.searches.hits`
- `passport_statuses.searches.misses`
- `passport_statuses.searches.non_unique`
> Add some metrics for ESRF requests and passport statuses

- src/main/java/ca/gov/dtsstn/passport/api/web/model/CertificateApplicationIdentificationModel.java
- src/main/java/ca/gov/dtsstn/passport/api/web/model/CertificateApplicationModel.java
- src/main/java/ca/gov/dtsstn/passport/api/web/validation/CertificateApplicationIdentification.java
- src/main/java/ca/gov/dtsstn/passport/api/web/validation/CertificateApplicationIdentificationValidator.java
Allow `"IdentificationCategoryText": "Manifest Number"` to be sent as an optional (nullable or empty) entry.
> Update CertificateApplicationIdentification validation

- README.md
- src/main/java/ca/gov/dtsstn/passport/api/actuate/PersistentHttpTraceRepository.java
- src/main/resources/application.yaml
Add http request repository filtering pattern like `RequestLoggingFilter` but it's only applied to persistence DB repository not for in-memory http trace.
[ADO-1293](https://dev.azure.com/DTS-STN/passport-status/_workitems/edit/1293)
> Add http request repository filtering

- src/main/java/ca/gov/dtsstn/passport/api/web/model/CertificateApplicationIdentificationModel.java
- src/main/resources/db-migrations/common/v0-[common]-schema-init.sql
update our character limit on the manifest number field to match IRCC at 50 characters.
> Updated char limit from 32 to 50 on manifest number field

- src/main/java/ca/gov/dtsstn/passport/api/web/ElectronicServiceRequestController.java
Fix error: Cannot build NotificationSentEvent, some of required attributes are not set [surname]
```bash
java.lang.IllegalStateException: Cannot build NotificationSentEvent, some of required attributes are not set [surname]
at ca.gov.dtsstn.passport.api.event.ImmutableNotificationSentEvent$Builder.build(ImmutableNotificationSentEvent.java:396) ~[classes/:na]
ImmutableNotificationSentEvent.java:396
at ca.gov.dtsstn.passport.api.web.ElectronicServiceRequestController.lambda$0(ElectronicServiceRequestController.java:107) ~[classes/:na]
ElectronicServiceRequestController.java:107
at java.base/java.util.Optional.ifPresentOrElse(Optional.java:196) ~[na:na]
Optional.java:196
at ca.gov.dtsstn.passport.api.web.ElectronicServiceRequestController.create(ElectronicServiceRequestController.java:97) …
```
> Fix error Cannot build NotificationSentEvent

- src/main/java/ca/gov/dtsstn/passport/api/web/ElectronicServiceRequestController.java
- src/test/java/ca/gov/dtsstn/passport/api/web/ElectronicServiceRequestControllerTests.java
Change response code when multiple ESRF numbers are found for a search query from HTTP422 to HTTP202.
(also added unit tests for `ElectronicServiceRequestController`)
See: https://dev.azure.com/DTS-STN/passport-status/_workitems/edit/1920
> ADO1920 -- duplicate ESRF HTTP202

- src/main/resources/db-migrations/postgresql/v0.1-[vendor]-schema-init.sql
This change was manually applied to all running environments including production.
> Add explicit schema name to unaccent function in remove_diacritics

- pom.xml
For added security, switch to the smaller runtime image.
> Switch to `run:base-cnb` container runtime

- pom.xml
Datafaker 1.7.0 pulls in 1.33, but spring managed versions overwrites it to 1.30 which has some vulnerabilities. So we need to force it to use the proper patched version.
> Patched snakeyml to 1.33 instead of managed 1.30

- src/main/java/ca/gov/dtsstn/passport/api/event/listener/NotificationEventListener.java
- src/main/java/ca/gov/dtsstn/passport/api/event/listener/PassportStatusEventListener.java
- src/main/java/ca/gov/dtsstn/passport/api/web/AuthenticationErrorHandler.java
- src/main/java/ca/gov/dtsstn/passport/api/web/PassportStatusController.java
Added event logging to the event handlers, in that it now logs to standard out, to satisfy the groups we're sending these logs to that we're actually logging stuff.
Some of the warnings are actually useful, ie. if we ever actually somehow see an authentication error (which should be impossible) with an IP not what we'd expect from interop that's a signal something malicious is in the VNET.
Removed the extra controller methods for querying statuses (getAll and getById), since the application doesn't use them, and even though they're behind auth, not available outside the cluster, still seems it's easier to just not have to explain them.
PS: Squash commit this if that's not the default, VS Code had some weird auto-formatting enabled I wasn't aware of for java.
> Added event logging to std out, removed uneccessary controller endpoints

- src/main/java/ca/gov/dtsstn/passport/api/web/AuthenticationErrorHandler.java
Change is in preparation for upcoming Spring Boot 3.0 upgrade. The existing logging is inadequate for troubleshooting new Spring Security exceptions that are occurring after upgrade.
> Clean up authentication warning message

- .gitignore
- utils/.env.sample
- utils/passport-checker-populator.jmx
This PR adds a jMeter `.jmx` project that can be used to populate the passport database (via API calls) with random data.
> Add passport-checker-populator.jmx

- src/main/java/ca/gov/dtsstn/passport/api/data/SourceCodeRepository.java
- src/main/java/ca/gov/dtsstn/passport/api/data/entity/PassportStatusEntity.java
- src/main/java/ca/gov/dtsstn/passport/api/data/entity/SourceCodeEntity.java
- src/main/java/ca/gov/dtsstn/passport/api/service/domain/mapper/PassportStatusMapper.java
- src/main/resources/db-migrations/common/v3-[common]-add-source-code-table.sql
- Add new `source_code` lookup table that represents downstream data source (IRIS, GCMS, Tempo)
- Populate `source_code` lookup table with existing known sources (IRIS, GCMS, Tempo)
- Alter `passport_status` table and a new `source_code_id` column which joins to new `source_code` table; set the default value to IRIS so existing rows will be properly populated
- Alter `passport_status` table to remove default `source_code_id`
- Update JPA entities and add `SourceCodeRepository`
- Hack `PassportStatusMapper` to ensure all new requests have the source ID set to IRIS
As of right now, the public-facing interface for this API has not changed. The source system will be automatically set to IRIS for all new requests. In a future PR, the source system field will be exposed and all consumers of …
> Add `source_code` DB table and necessary migrations

- src/main/java/ca/gov/dtsstn/passport/api/event/PassportStatusSearchEvent.java
- src/main/java/ca/gov/dtsstn/passport/api/web/PassportStatusController.java
Added additional audit data to `PassportStatusSearchEvent`: `applicationRegisterSids` and `passportStatus`. These fields are marked as `@Nullable`, meaning they may be null, depending on the search result (hit, miss, non-unique).
``` json
{
"applicationRegisterSids": null,
"dateOfBirth": "2000-01-01",
"email": null,
"fileNumber": "D120DE30",
"givenName": "Goober",
"surname": "Baker",
"result": "MISS",
"passportStatus": null,
"timestamp": "2023-06-08T10:34:54.179142057Z"
}
```
Notice the new `applicationRegisterSids` field which displays the SIDs of the matching passport statuses.
``` json
{
"applicationRegisterSids": [
"ab15c32d-961e-3895-ba8a-9e4c26ccadf5",
"3186356f-eb4a-4f8a-9603-cbb391355ca4"
],
"dateOfBirth": "2000-01-01",
"email": null,
"fileNumber": "D120DE30",
"givenName": "Greg", …
```
> Add search result data to search events

- src/main/java/ca/gov/dtsstn/passport/api/data/UuidGenerator.java
- src/test/java/ca/gov/dtsstn/passport/api/data/UuidGeneratorTests.java
The new version of hibernate used in Spring Boot 3.1.x caused a serialization warning in `UuidGenerator`. The tests also needed some love.
> Fix warning in UuidGenerator; improve test

- pom.xml
We've decided to remove that plugin since the reports not being use or read. It is also requires to update it to version 9 and it add some complexity like the need to use an API key to fetch the database faster.
https://github.com/jeremylong/DependencyCheck#900-upgrade-notice
> Remove dependency-check-maven plugin

- pom.xml
Added postgresql flyway support.
Modular Flyway V10 (No database found to handle or Unsupported Database)
https://github.com/flyway/flyway/issues/3780
> Add flyway-database-postgresql dependency

- src/main/java/ca/gov/dtsstn/passport/api/config/properties/ApplicationProperties.java
- src/main/java/ca/gov/dtsstn/passport/api/config/properties/FeatureFlagsProperties.java
- src/main/java/ca/gov/dtsstn/passport/api/config/properties/HideManifestProperties.java
- src/main/java/ca/gov/dtsstn/passport/api/data/entity/StatusCodeEntity.java
- src/main/java/ca/gov/dtsstn/passport/api/web/model/mapper/CertificateApplicationModelMapper.java
- src/main/resources/application-local.yaml.sample
- src/test/java/ca/gov/dtsstn/passport/api/web/model/mapper/CertificateApplicationModelMapperTests.java
List of proposed changes:
- Add configuration properties for hiding the manifest numbers from client/public view
> Add feature-flag for hiding manifest numbers

- pom.xml
- src/main/java/ca/gov/dtsstn/passport/api/data/annotation/EntityId.java
- src/main/java/ca/gov/dtsstn/passport/api/data/entity/AbstractEntity.java
- src/main/java/ca/gov/dtsstn/passport/api/data/init/DatabaseInitializer.java
- src/main/java/ca/gov/dtsstn/passport/api/service/NotificationService.java
- src/test/java/ca/gov/dtsstn/passport/api/WebMvcIT.java
- src/test/java/ca/gov/dtsstn/passport/api/web/ElectronicServiceRequestControllerTests.java
- src/test/java/ca/gov/dtsstn/passport/api/web/model/mapper/CertificateApplicationModelMapperTests.java
Things that have changed:
- datafaker deprecated its `DataAndTime` provider, creating a new `TimeAndDate` provider based off the `java.time.*` API
- Hibernate has changed how ID generation works and now you can no longer pre-calculate IDs before persisting a new entity (at least, I couldn't figure out how)
> Fix broken database initializer and fix deprecations/warnings

- src/main/java/ca/gov/dtsstn/passport/api/data/PassportStatusRepository.java
- src/main/java/ca/gov/dtsstn/passport/api/service/PassportStatusService.java
- src/main/java/ca/gov/dtsstn/passport/api/web/PassportStatusController.java
- src/main/java/ca/gov/dtsstn/passport/api/web/model/assembler/GetCertificateApplicationRepresentationModelAssembler.java
- src/test/java/ca/gov/dtsstn/passport/api/service/PassportStatusServiceTests.java
Add new passport status controller endpoint to search for 'single name' applications; update related service and repository.
> Add endpoint for single-name search
