DTS-STN/passport-status-api

- pom.xml
> Describes the committers of a project

- src/main/java/ca/gov/dtsstn/passport/api/web/PassportStatusController.java
- src/main/java/ca/gov/dtsstn/passport/api/web/annotation/Schema.java
- src/main/java/ca/gov/dtsstn/passport/api/web/model/PassportStatusSearchModel.java
- src/main/java/ca/gov/dtsstn/passport/api/web/model/error/BadRequestErrorModel.java
Cleaning up some swagger annotations to make them fit their intended usage.
> Clean up some SpringDoc annotations

- pom.xml
- src/main/java/ca/gov/dtsstn/passport/api/config/SpringDocConfig.java
- src/main/java/ca/gov/dtsstn/passport/api/config/WebSecurityConfig.java
- src/main/java/ca/gov/dtsstn/passport/api/security/AuthoritiesConstants.java
- src/main/java/ca/gov/dtsstn/passport/api/security/JwtGrantedAuthoritiesConverter.java
- src/main/java/ca/gov/dtsstn/passport/api/web/PassportStatusController.java
- src/main/resources/application-local.yaml.sample
- src/main/resources/application.yaml
This PR add OAuth2 authentication and secure endpoints.
> Add OAuth2 authentication

- src/main/java/ca/gov/dtsstn/passport/api/web/PassportStatusController.java
As per title. Using `async=false` triggers a 500 error (intentionally) which is annoying for consumers.
> Fix search

- src/main/java/ca/gov/dtsstn/passport/api/web/ApiErrorHandler.java
- src/main/java/ca/gov/dtsstn/passport/api/web/PassportStatusController.java
Fall back to Spring's default `ResponseEntityExceptionHandler` so otherwise missed exceptions would be handled.
> Update exception handling

- src/main/java/ca/gov/dtsstn/passport/api/config/SpringDocConfig.java
Something's broken.. will look at it more later.
> Disable swagger server list

- src/main/java/ca/gov/dtsstn/passport/api/web/model/AbstractResponseModelAssembler.java
Existing code was adding an additional field in the JSON response.
> Fix broken CollectionMmodel wrapping

- src/main/java/ca/gov/dtsstn/passport/api/web/PassportStatusController.java
- src/main/java/ca/gov/dtsstn/passport/api/web/SecurityController.java
- src/main/java/ca/gov/dtsstn/passport/api/web/annotation/Authorities.java
- src/main/java/ca/gov/dtsstn/passport/api/web/model/AbstractResponseModel.java
- src/main/java/ca/gov/dtsstn/passport/api/web/model/PassportStatusReadResponseModel.java
- src/test/java/ca/gov/dtsstn/passport/api/web/SecurityControllerTests.java
Fields annotated with `@JsonView({ Authorities.Authenticated.class })` will now be hidden from anonymous users.
> Filter output by on auth state

- src/main/resources/db-migrations/common/v0-[common]-schema-init.sql
Increasing column sizes to accommodate incoming interop data.
> Update database schema

- src/main/java/ca/gov/dtsstn/passport/api/web/model/CreateCertificateApplicationRequestModelMapper.java
- src/test/java/ca/gov/dtsstn/passport/api/web/model/CreateCertificateApplicationRequestModelMapperTests.java
Test coverage is _almost_ 100%. There are some `null` returns that aren't being tested, but I think that's okay.
ex: (red = not tested)
> Add NIEM model mapper and unit test

- src/main/java/ca/gov/dtsstn/passport/api/web/ApiErrorHandler.java
- src/main/java/ca/gov/dtsstn/passport/api/web/model/PersonNameModel.java
- src/main/java/ca/gov/dtsstn/passport/api/web/validation/JacksonPropertyNodeNameProvider.java
- src/main/java/ca/gov/dtsstn/passport/api/web/validation/JacksonValidatorFactoryBean.java
This PR adds correct property discovery..
Was:
`certificateApplication.certificateApplicationApplicant.birthDate`
Now:
`$.CertificateApplication.CertificateApplicationApplicant.BirthDate`
> Add proper ConstraintViolation property discovery

- src/main/java/ca/gov/dtsstn/passport/api/web/model/BirthDateModel.java
- src/main/java/ca/gov/dtsstn/passport/api/web/model/CertificateApplicationApplicantModel.java
- src/main/java/ca/gov/dtsstn/passport/api/web/model/CertificateApplicationDateModel.java
- src/main/java/ca/gov/dtsstn/passport/api/web/model/CertificateApplicationIdentificationModel.java
- src/main/java/ca/gov/dtsstn/passport/api/web/model/CertificateApplicationModel.java
- src/main/java/ca/gov/dtsstn/passport/api/web/model/CertificateApplicationModelMapper.java
- src/main/java/ca/gov/dtsstn/passport/api/web/model/CertificateApplicationStatusModel.java
- src/main/java/ca/gov/dtsstn/passport/api/web/model/CreateCertificateApplicationRequestModel.java
- src/main/java/ca/gov/dtsstn/passport/api/web/model/PersonContactInformationModel.java
- src/main/java/ca/gov/dtsstn/passport/api/web/model/PersonNameModel.java
Tightened up some of the validation and added default return values for the models.
> Update models in preparation for upcoming validation changes

- src/main/java/ca/gov/dtsstn/passport/api/data/entity/EventLogEntity.java
- src/main/java/ca/gov/dtsstn/passport/api/data/entity/EventLogTypeEntity.java
- src/main/resources/db-migrations/common/v0-[common]-schema-init.sql
Add a new table to the database to hold important API events.
> Incremental commit: add event_log db table

- src/main/java/ca/gov/dtsstn/passport/api/web/ApiErrorHandler.java
- src/main/java/ca/gov/dtsstn/passport/api/web/PassportStatusController.java
- src/main/java/ca/gov/dtsstn/passport/api/web/model/BirthDateModel.java
- src/main/java/ca/gov/dtsstn/passport/api/web/model/CertificateApplicationDateModel.java
- src/main/java/ca/gov/dtsstn/passport/api/web/model/CertificateApplicationIdentificationModel.java
- src/main/java/ca/gov/dtsstn/passport/api/web/model/CertificateApplicationStatusModel.java
- src/main/java/ca/gov/dtsstn/passport/api/web/model/CreateElectronicServiceRequestModel.java
- src/main/java/ca/gov/dtsstn/passport/api/web/model/PersonContactInformationModel.java
- src/main/java/ca/gov/dtsstn/passport/api/web/model/PersonNameModel.java
- src/main/java/ca/gov/dtsstn/passport/api/web/validation/Boolean.java
- src/main/java/ca/gov/dtsstn/passport/api/web/validation/BooleanValidator.java
As per title.. just added some improved error handling.
> Imrove error handling

- pom.xml
- src/main/java/ca/gov/dtsstn/passport/api/data/StatusCodeRepository.java
- src/main/java/ca/gov/dtsstn/passport/api/data/entity/PassportStatusEntity.java
- src/main/java/ca/gov/dtsstn/passport/api/data/entity/StatusCodeEntity.java
- src/main/java/ca/gov/dtsstn/passport/api/data/init/DatabaseInitializer.java
- src/main/java/ca/gov/dtsstn/passport/api/service/PassportStatusService.java
- src/main/java/ca/gov/dtsstn/passport/api/service/StatusCodeService.java
- src/main/java/ca/gov/dtsstn/passport/api/service/domain/PassportStatus.java
- src/main/java/ca/gov/dtsstn/passport/api/service/domain/StatusCode.java
- src/main/java/ca/gov/dtsstn/passport/api/service/domain/mapper/PassportStatusMapper.java
- src/main/java/ca/gov/dtsstn/passport/api/service/domain/mapper/StatusCodeMapper.java
- src/main/java/ca/gov/dtsstn/passport/api/web/PassportStatusController.java
- src/main/java/ca/gov/dtsstn/passport/api/web/model/assembler/GetCertificateApplicationRepresentationModelAssembler.java
- src/main/java/ca/gov/dtsstn/passport/api/web/model/mapper/CertificateApplicationModelMapper.java
- src/main/java/ca/gov/dtsstn/passport/api/web/model/mapper/ElectronicServiceRequestModelMapper.java
- src/main/java/ca/gov/dtsstn/passport/api/web/validation/PassportStatusCodeValidator.java
- src/main/resources/db-migrations/common/v0-[common]-schema-init.sql
- src/test/java/ca/gov/dtsstn/passport/api/service/PassportStatusServiceTests.java
- src/test/java/ca/gov/dtsstn/passport/api/web/model/mapper/CertificateApplicationModelMapperTests.java
- src/test/java/ca/gov/dtsstn/passport/api/web/validation/PassportStatusCodeValidatorTests.java
[1190 - Look up status codes from database table](https://dev.azure.com/DTS-STN/passport-status/_workitems/edit/1190/)
Replace status code enum with status code lookup table.
An issue was found with H2 database collation and I've added ICU4J as project dependency. Please look at the issue that Greg written to the H2 database project.
https://github.com/h2database issues #3665
> 1190 - Look up status codes from database table

- pom.xml
- src/main/java/ca/gov/dtsstn/passport/api/config/CacheConfig.java
- src/main/java/ca/gov/dtsstn/passport/api/config/cache/CaffeineCacheFactory.java
- src/main/java/ca/gov/dtsstn/passport/api/service/StatusCodeService.java
- src/main/resources/application.yaml
- src/test/java/ca/gov/dtsstn/passport/api/config/cache/CaffeineCacheFactoryTests.java
As per title. Cache TTL is set to 5 minutes.
> Add caching for StatusCodeService

- README.md
- src/main/java/ca/gov/dtsstn/passport/api/data/PassportStatusRepository.java
- src/main/java/ca/gov/dtsstn/passport/api/data/entity/EmailRequestEntity.java
- src/main/java/ca/gov/dtsstn/passport/api/data/entity/PassportStatusEntity.java
- src/main/java/ca/gov/dtsstn/passport/api/data/init/DatabaseInitializer.java
- src/main/java/ca/gov/dtsstn/passport/api/event/NotificationNotSentEvent.java
- src/main/java/ca/gov/dtsstn/passport/api/event/NotificationRequestedEvent.java
- src/main/java/ca/gov/dtsstn/passport/api/event/PassportStatusSearchEvent.java
- src/main/java/ca/gov/dtsstn/passport/api/service/PassportStatusService.java
- src/main/java/ca/gov/dtsstn/passport/api/service/domain/PassportStatus.java
- src/main/java/ca/gov/dtsstn/passport/api/web/ElectronicServiceRequestController.java
- src/main/java/ca/gov/dtsstn/passport/api/web/PassportStatusController.java
- src/main/java/ca/gov/dtsstn/passport/api/web/model/assembler/GetCertificateApplicationRepresentationModelAssembler.java
- src/main/java/ca/gov/dtsstn/passport/api/web/model/mapper/CertificateApplicationModelMapper.java
- src/main/java/ca/gov/dtsstn/passport/api/web/model/mapper/ElectronicServiceRequestModelMapper.java
- src/main/resources/db-migrations/common/v0-[common]-schema-init.sql
- src/main/resources/db-migrations/postgresql/v0.1-[vendor]-schema-init.sql
- src/test/java/ca/gov/dtsstn/passport/api/service/PassportStatusServiceTests.java
- src/test/java/ca/gov/dtsstn/passport/api/web/model/mapper/CertificateApplicationModelMapperTests.java
- src/test/java/ca/gov/dtsstn/passport/api/web/model/mapper/ElectronicServiceRequestModelMapperTests.java
Self-explanatory
- Rename firstName to givenName
- Rename lastName to surname
[1211 - Rename PassportStatusEntity's First, LastName fields ](https://dev.azure.com/DTS-STN/passport-status/_workitems/edit/1211/)
> 1211 rename first and last name fields

- src/main/java/ca/gov/dtsstn/passport/api/data/entity/EventLogEntity.java
- src/main/java/ca/gov/dtsstn/passport/api/event/listener/PassportStatusEventListener.java
> Implement PassportStatusEvent listeners

- src/main/java/ca/gov/dtsstn/passport/api/event/listener/MetricsGeneratingEventListener.java
- src/main/java/ca/gov/dtsstn/passport/api/web/validation/PassportStatusCodeValidator.java
- src/main/resources/db-migrations/common/v0-[common]-schema-init.sql
- src/main/resources/db-migrations/common/v1-[common]-data-init.sql
The official list of status codes has been provided.
| Code | Description |
|-------|--------------|
|1 | File being processed |
| 2 | Passport will be issued |
| 3 | Passport Issued & Shipping Canada Post |
| 4 | Passport Issued & Shipping Fedex |
| 5 | Not acceptable for processing |
| 99 | Not on table, but used for files that were previously sent to DTS as legitimate files, but are now missing information that would prevent their sending an update to DTS on a following day - this will provide no record found message |
> Add valid status codes

- pom.xml
- src/main/resources/application.yaml
Add actuator and maven dependency for prometheus.
> Re-add prometheus support

- src/main/resources/db-migrations/common/v1-[common]-data-init.sql
- src/test/java/ca/gov/dtsstn/passport/api/web/model/mapper/CertificateApplicationModelMapperTests.java
Update to the satus code provided by Mckittrick, Jack [NC] at 10:28 a.m. 
| Code | Description |
| ----------- | ----------- |
| 1 | File being processed |
| 2 | Passport Issued and Ready for Pickup |
| 3 | Passport Issued and Shipping Canada Post |
| 4 | Passport Issued and Shipping Fedex |
| 5 | Not acceptable for processing |
| 99 | Application No Longer Meets Criteria for Use in DTS |
> Update valid status codes

- src/main/java/ca/gov/dtsstn/passport/api/actuate/PersistentHttpTraceRepository.java
- src/main/java/ca/gov/dtsstn/passport/api/web/filter/RequestLoggingFilter.java
Rename isNotExcluded to isExcluded because it's confusing when using it.
> Rename isNotExcluded to isExcluded

- src/main/java/ca/gov/dtsstn/passport/api/config/properties/GcNotifyProperties.java
- src/main/java/ca/gov/dtsstn/passport/api/event/NotificationRequestedEvent.java
- src/main/java/ca/gov/dtsstn/passport/api/event/NotificationSentEvent.java
- src/main/java/ca/gov/dtsstn/passport/api/service/NotificationService.java
- src/main/java/ca/gov/dtsstn/passport/api/web/ElectronicServiceRequestController.java
- src/main/java/ca/gov/dtsstn/passport/api/web/model/ClientModel.java
- src/main/java/ca/gov/dtsstn/passport/api/web/model/PersonPreferredLanguageModel.java
- src/main/java/ca/gov/dtsstn/passport/api/web/validation/ValueOfEnum.java
- src/main/java/ca/gov/dtsstn/passport/api/web/validation/ValueOfEnumValidator.java
- src/main/resources/application-local.yaml.sample
- src/main/resources/application.yaml
- src/test/java/ca/gov/dtsstn/passport/api/web/validation/ValueOfEnumTests.java
- src/test/resources/application-test.yaml
[ADO-1564](https://dev.azure.com/DTS-STN/passport-status/_workitems/edit/1564/)
Get ESRF - Email Text: Add the ability to send the file number email in the user's preferred language (based on UI locale)
> Add ability to send File Number email in client preferred language

- src/main/java/ca/gov/dtsstn/passport/api/event/listener/MetricsGeneratingEventListener.java
Realign metrics messages based on current status codes.
> Fix metrics assignment based on status code

- src/main/java/ca/gov/dtsstn/passport/api/data/PassportStatusRepository.java
- src/main/java/ca/gov/dtsstn/passport/api/data/init/DatabaseInitializer.java
Make searching for statuses exact.
See <https://dev.azure.com/DTS-STN/passport-status/_workitems/edit/1892>
Also added some test data to the `DatabaseInitializer` class that can be used to test that everything works.
> ADO1892 -- exact search

- pom.xml
- **Gitlog plugin:** 1.13.17 → 1.14.0
- **Immutables:** 2.9.2 → 2.9.3
- **Springdoc:** 1.6.13 → 1.6.14
> Bump dependencies to latest

- src/main/java/ca/gov/dtsstn/passport/api/config/CacheConfig.java
- src/main/java/ca/gov/dtsstn/passport/api/service/NotificationService.java
- src/main/resources/application.yaml
Added a rate limit of one email per ESRF per minute.
> ADO1936 -- SPAM reduction strategy

- pom.xml
> Bump Spring Boot to v2.7.8

- src/main/java/ca/gov/dtsstn/passport/api/web/ElectronicServiceRequestController.java
Add logging/auditing to a failed call to GC Notify call.
> Emit `NotificationNotSentEvent` when call to GCNotify fails

- pom.xml
Note: this fixes CVE-2023-20860.
> Bump Spring Boot to v2.7.10

- src/main/java/ca/gov/dtsstn/passport/api/config/WebSecurityConfig.java
Trivial refactoring in preparation for upcoming Spring Boot 3.0 upgrade.
> Refactor WebSecurityConfig (preparation for SB3.0)

- pom.xml
See: https://www.cve.org/CVERecord?id=CVE-2022-1471
> CVE-2022-1471 (snakeyaml arbitrary code execution)

- pom.xml
> Bump Spring Boot to v3.0.7

- src/main/resources/application.yaml
Dynatrace config keys recently changed. This PR fixes them.
> Fix Dynatrace configuration deprecation

- src/main/java/ca/gov/dtsstn/passport/api/data/init/DatabaseInitializer.java
> Fix `DatabaseInitializer`

- pom.xml
- src/main/java/ca/gov/dtsstn/passport/api/data/init/DatabaseInitializer.java
- src/main/java/ca/gov/dtsstn/passport/api/web/ChangelogEndpoint.java
This update broke how `@ConfigurationProperties` worked, so I had to fix two classes in the application to use `@Value` for their configurations.
> Bump Spring Boot to v3.1.1

- pom.xml
> Bump Spring Boot to v3.1.2

- README.md
- docker/Dockerfile-MavenBuild
- pom.xml
The `passport-status-api-builder` container has been updated and pushed to dev ACR.
> Upgrade Java to version 21

- pom.xml
Fix our TC pipeline
Context
https://stackoverflow.com/questions/77376239/building-spring-boot-3-1-5-image-using-paketobuildpacks-via-maven-plugin-is-not/77379850#77379850
Image Customizations
https://docs.spring.io/spring-boot/docs/current/maven-plugin/reference/htmlsingle/#build-image.customization
> Use Spring Boot default CNB builders

- pom.xml
Note to reviewer: all tests pass after this change.
> Bump Spring Boot to v3.2.2

- pom.xml
> Bump Spring Boot to v3.2.3

- pom.xml
Bumped a few other dependencies, too.
**All tests are passing.**
> Bump Spring Boot to v3.3.0

- pom.xml
> Bump dependencies (spring boot)

- .github/dependabot.yml
> Fix typo in dependabot configuration
